name: Title to Labels
description: Cleans up the titles of issues and PRs from common opening keywords.
branding:
  icon: minimize-2
  color: yellow
inputs:
  keywords:
    description: The keywords to look for, separed by comma or newline. Case-insensitive.
  labels:
    description: The labels to apply when one of the keywords was found. Optional.
  GITHUB_TOKEN:
    description: 'The automatically-generated token, set this to \$\{\{ secrets.GITHUB_TOKEN \}\}'
runs:
  using: node12
  main: distribution/index.js
