name: Title to Labels
description: Cleans up the titles of issues and PRs from common opening keywords.
branding:
  icon: minimize-2
  color: yellow
inputs:
  keywords:
    description: The keywords to look for, separed by comma or newline. Case-insensitive.
  labels:
    description: The labels to apply when one of the keywords was found. Optional.
  update-title:
    description: Whether to update the title by removing the keyword. Set to `false` to only add labels without changing the title. Default is `true`.
  GITHUB_TOKEN:
    description: 'The automatically-generated token, set this to \$\{\{ secrets.GITHUB_TOKEN \}\}'
    deprecated: Use `token` instead
  token:
    description: 'The automatically-generated token, set this to \$\{\{ secrets.GITHUB_TOKEN \}\}'
runs:
  using: node20
  main: distribution/index.js
