name: Build

on:
  - pull_request
  - push

jobs:
  Update files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Update built files
